NDefines.NCountry.POLITICAL_POWER_UPPER_CAP = 5000.0

-- Argentina Rise accessibility override:
-- keep enemy intelligence estimates readable without requiring La Resistance spy networks.
NDefines.NCountry.MAX_INTELLIGENCE_DATA_DEVIATION = 0.0
NDefines.NCountry.MAX_INTELLIGENCE_MILITARY_DATA_DEVIATION = 0.0
NDefines.NCountry.MAX_INTELLIGENCE_NAVY_DATA_DEVIATION = 0.0
NDefines.NCountry.MAX_INTELLIGENCE_AIR_DATA_DEVIATION = 0.0
NDefines.NCountry.MAX_INTELLIGENCE_CONVOY_DATA_DEVIATION = 0.0
NDefines.NCountry.MAX_INTELLIGENCE_INDUSTRY_DATA_DEVIATION = 0.0
NDefines.NCountry.MAX_INTELLIGENCE_MANPOWER_DATA_DEVIATION = 0.0
NDefines.NCountry.MAX_INTELLIGENCE_FIELDED_MANPOWER_DATA_DEVIATION = 0.0

-- Intel ledger visibility:
-- remove fuzzy ranges for the main enemy overview numbers.
NDefines.NIntel.CIVILIAN_PRODUCTION_RANGE_INTEL_MIN = 0.0
NDefines.NIntel.CIVILIAN_PRODUCTION_RANGE_INTEL_MAX = 0.0
NDefines.NIntel.CIVILIAN_PRODUCTION_INTEL_RANGE_AT_LOWEST_INTEL = 0.0
NDefines.NIntel.CIVILIAN_MANPOWER_RANGE_INTEL_MIN = 0.0
NDefines.NIntel.CIVILIAN_MANPOWER_RANGE_INTEL_MAX = 0.0
NDefines.NIntel.CIVILIAN_MANPOWER_INTEL_RANGE_AT_LOWEST_INTEL = 0.0
NDefines.NIntel.CIVILIAN_CONVOYS_RANGE_INTEL_MIN = 0.0
NDefines.NIntel.CIVILIAN_CONVOYS_INTEL_RANGE_AT_LOWEST_INTEL = 0.0

NDefines.NIntel.ARMY_ARMY_COUNT_RANGE_INTEL_MIN = 0.0
NDefines.NIntel.ARMY_ARMY_COUNT_RANGE_INTEL_MAX = 0.0
NDefines.NIntel.ARMY_ARMY_COUNT_RANGE_INTEL_RANGE_AT_LOWEST_INTEL = 0.0
NDefines.NIntel.ARMY_SPECIAL_FORCES_COUNT_RANGE_INTEL_RANGE_AT_LOWEST_INTEL = 0.0
NDefines.NIntel.ARMY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MIN = 0.0
NDefines.NIntel.ARMY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MAX = 0.0
NDefines.NIntel.ARMY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_RANGE_AT_LOWEST_INTEL = 0.0

NDefines.NIntel.NAVY_FLEET_COUNT_INTEL_MIN = 0.0
NDefines.NIntel.NAVY_FLEET_COUNT_INTEL_MAX = 0.0
NDefines.NIntel.NAVY_FLEET_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.0
NDefines.NIntel.NAVY_TASKFORCE_COUNT_INTEL_MIN = 0.0
NDefines.NIntel.NAVY_TASKFORCE_COUNT_INTEL_MAX = 0.0
NDefines.NIntel.NAVY_TASKFORCE_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.0
NDefines.NIntel.NAVY_SHIP_COUNT_INTEL_MIN = 0.0
NDefines.NIntel.NAVY_SHIP_COUNT_INTEL_MAX = 0.0
NDefines.NIntel.NAVY_SHIP_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.0
NDefines.NIntel.NAVY_SHIP_TYPE_COUNT_INTEL_MIN = 0.0
NDefines.NIntel.NAVY_SHIP_TYPE_COUNT_INTEL_MAX = 0.0
NDefines.NIntel.NAVY_SHIP_TYPE_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.0
NDefines.NIntel.NAVY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MIN = 0.0
NDefines.NIntel.NAVY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MAX = 0.0
NDefines.NIntel.NAVY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_RANGE_AT_LOWEST_INTEL = 0.0

NDefines.NIntel.AIR_AIRWING_COUNT_INTEL_MIN = 0.0
NDefines.NIntel.AIR_AIRWING_COUNT_INTEL_MAX = 0.0
NDefines.NIntel.AIR_AIRWING_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.0
NDefines.NIntel.AIR_WING_TYPE_COUNT_INTEL_MIN = 0.0
NDefines.NIntel.AIR_WING_TYPE_COUNT_INTEL_MAX = 0.0
NDefines.NIntel.AIR_WING_TYPE_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.0
NDefines.NIntel.AIR_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MIN = 0.0
NDefines.NIntel.AIR_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MAX = 0.0
NDefines.NIntel.AIR_DEPLOYED_MANPOWER_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.0
